version: '3.9'

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-9000}:9000"  # Set a default value of 9000 if APP_PORT is not set
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_PORT=${APP_PORT:-9000}  # Set a default value of 9000 if APP_PORT is not set
    depends_on:
      - redis
      - postgres
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    command: sh -c "chmod -R a+rwx /var/lib/postgresql/data"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data